import {afterEach,describe,expect,test} from "bun:test";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";import {resolve} from "node:path";
import {DurableStore} from "../core/schema";import {dispatchOnce,reconcileRunning} from "./dispatcher";
const roots:string[]=[];afterEach(async()=>{delete process.env.DISPATCH_COUNTER_PATH;delete process.env.DISPATCH_WORK_MS;delete process.env.DISPATCH_CHILD_PID_PATH;await Promise.all(roots.splice(0).map(x=>rm(x,{recursive:true,force:true})))});
async function fixture(retryBudget=0,worker=[process.execPath,resolve(import.meta.dir,"../tests/fixtures/noop-worker.ts")]){const root=await mkdtemp(resolve(tmpdir(),"v3-dispatch-"));roots.push(root);const storePath=resolve(root,"state.sqlite"),s=new DurableStore(storePath);s.createMission({id:"mission-1",correlationId:"corr-1",acceptanceId:"ma-1"});s.createManager({id:"manager-1",missionId:"mission-1",parentId:"mission-1",depth:1});s.createLane({id:"lane-1",missionId:"mission-1",managerId:"manager-1",parentId:"manager-1",depth:2,retryBudget,acceptanceId:"a-1"});s.close();return{root,storePath,runtimeDir:resolve(root,"runtime"),worker}}
const row=(p:string)=>{const s=new DurableStore(p),r=s.getLane("lane-1")!;s.close();return r};
const pidAlive=(pid:number)=>{try{process.kill(pid,0);return true}catch{return false}};
describe("canonical fenced dispatch",()=>{
 test("claims once and persists schema-validated commit evidence",async()=>{const o=await fixture();await Promise.all([dispatchOnce(o),dispatchOnce(o)]);const r=row(o.storePath);expect(r.fencingToken).toBe(1);expect(r.terminalVerdict).toBe("clean");expect(await readFile(r.terminalReportPath!,"utf8")).toContain(`commit: ${r.terminalSha}`)});
 test("ack timeout terminates original before retry can launch",async()=>{const o=await fixture(1,[process.execPath,"-e",`process.on('SIGTERM',()=>setTimeout(()=>process.exit(0),80));setInterval(()=>{},100)`]);await dispatchOnce({...o,acknowledgementMs:30});expect(row(o.storePath).state).toBe("ready");const counter=resolve(o.root,"launches");process.env.DISPATCH_COUNTER_PATH=counter;await dispatchOnce({...o,worker:[process.execPath,resolve(import.meta.dir,"../tests/fixtures/noop-worker.ts")]});expect(row(o.storePath).terminalVerdict).toBe("clean");expect((await readFile(counter,"utf8")).trim()).toBe("launch")});
 test("reconciliation kills the real indefinitely-live child from the spawn-to-record crash window",async()=>{const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/never-exit-worker.ts")]),childPidPath=resolve(o.root,"child.pid");process.env.DISPATCH_CHILD_PID_PATH=childPidPath;let wrapperPid=0,childPid=0;
  try{await expect(dispatchOnce({...o,afterSpawnBeforePersist:async()=>{const intentPath=resolve(o.runtimeDir,"lane-1","attempt-1","worker-intent.json");for(let n=0;n<200;n++){try{const i=JSON.parse(await readFile(intentPath,"utf8"));if(i.phase==="identified")wrapperPid=i.pid}catch{}try{childPid=Number(await readFile(childPidPath,"utf8"))}catch{}if(wrapperPid&&childPid)break;await Bun.sleep(5)}expect(row(o.storePath).state).toBe("claimed");expect(wrapperPid).toBeGreaterThan(0);expect(childPid).toBeGreaterThan(0);expect(pidAlive(wrapperPid)).toBe(true);expect(pidAlive(childPid)).toBe(true);throw new Error("crash window")}})).rejects.toThrow("crash window");
   expect(await reconcileRunning(o)).toBe(1);for(let n=0;n<100&&(pidAlive(wrapperPid)||pidAlive(childPid));n++)await Bun.sleep(10);expect(pidAlive(wrapperPid)).toBe(false);expect(pidAlive(childPid)).toBe(false);expect(row(o.storePath).terminalVerdict).toBe("NO-GO")
  }finally{for(const pid of [wrapperPid,childPid])if(pid&&pidAlive(pid))process.kill(pid,"SIGKILL")}});
 test("recovers a live worker after PID persistence and before release",async()=>{
  const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/gated-worker.ts")]),counter=resolve(o.root,"launches");process.env.DISPATCH_COUNTER_PATH=counter;let pid=0;
  try {
   await expect(dispatchOnce({...o,afterPersistBeforeRelease:async r=>{pid=r.workerPid!;expect(pid).toBeGreaterThan(0);expect(await Bun.file(resolve(o.runtimeDir,"lane-1","attempt-1","release")).exists()).toBe(false);expect(pidAlive(pid)).toBe(true);throw new Error("post-pid crash")}})).rejects.toThrow("post-pid crash");
   expect(row(o.storePath).state).toBe("running");expect(await reconcileRunning({...o,terminalMs:5000})).toBe(1);expect(row(o.storePath).terminalVerdict).toBe("clean");
   for(let i=0;i<100&&pidAlive(pid);i++)await Bun.sleep(10);
   expect(pidAlive(pid)).toBe(false);expect((await readFile(counter,"utf8")).trim()).toBe("launch");
  } finally {if(pid&&pidAlive(pid))process.kill(pid,"SIGKILL")}
 });
 test("reconciles a claimed row carrying authentic terminal evidence",async()=>{const o=await fixture();const s=new DurableStore(o.storePath),c=s.claimLane("lane-1","owner",30000),r=s.getLane("lane-1")!;s.close();const dir=resolve(o.runtimeDir,"lane-1",`attempt-${c.fencingToken}`);await Bun.$`mkdir -p ${dir}`;const sha=Bun.spawnSync(["git","rev-parse","HEAD"]).stdout.toString().trim(),report=resolve(dir,"report.md");await writeFile(report,`lane: lane-1\nattempt: 1\ncommit: ${sha}\nresult: clean\nblocker: none\n`);await writeFile(resolve(dir,"terminal.json"),JSON.stringify({laneId:"lane-1",attempt:1,ownerToken:"owner",at:new Date().toISOString(),reportPath:report,sha,verdict:"clean"}));expect(await reconcileRunning(o)).toBe(1);expect(row(o.storePath).terminalVerdict).toBe("clean")});
 test("expired owner is fenced by an identified stale-lease takeover",async()=>{const o=await fixture(1),first=new DurableStore(o.storePath,()=>1000);const a=first.claimLane("lane-1","dispatcher-a",10);first.close();const second=new DurableStore(o.storePath,()=>1011),b=second.claimLane("lane-1","dispatcher-b",10);expect(b.fencingToken).toBe(a.fencingToken+1);expect(()=>second.acknowledgeLane("lane-1","dispatcher-a",a.fencingToken)).toThrow("stale or expired");second.close()});
 test("rejects synthetic SHA, foreign report, and mismatched attempt",async()=>{for(const kind of ["synthetic","foreign","attempt"]){const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/forged-worker.ts"),kind]);await dispatchOnce(o);expect(row(o.storePath).terminalVerdict).toBe("NO-GO");expect(await readFile(row(o.storePath).terminalReportPath!,"utf8")).toContain("terminal evidence invalid")}});
});
