import {afterEach,describe,expect,test} from "bun:test";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";import {resolve} from "node:path";
import {DurableStore} from "../core/schema";import {dispatchOnce,durableJson,reconcileRunning} from "./dispatcher";
const roots:string[]=[];afterEach(async()=>{delete process.env.DISPATCH_COUNTER_PATH;delete process.env.DISPATCH_WORK_MS;delete process.env.DISPATCH_CHILD_PID_PATH;await Promise.all(roots.splice(0).map(x=>rm(x,{recursive:true,force:true})))});
async function fixture(retryBudget=0,worker=[process.execPath,resolve(import.meta.dir,"../tests/fixtures/noop-worker.ts")]){const root=await mkdtemp(resolve(tmpdir(),"v3-dispatch-"));roots.push(root);const storePath=resolve(root,"state.sqlite"),s=new DurableStore(storePath);s.createMission({id:"mission-1",correlationId:"corr-1",acceptanceId:"ma-1"});s.createManager({id:"manager-1",missionId:"mission-1",parentId:"mission-1",depth:1});s.createLane({id:"lane-1",missionId:"mission-1",managerId:"manager-1",parentId:"manager-1",depth:2,retryBudget,acceptanceId:"a-1"});s.close();return{root,storePath,runtimeDir:resolve(root,"runtime"),worker}}
const row=(p:string)=>{const s=new DurableStore(p),r=s.getLane("lane-1")!;s.close();return r};
const pidAlive=(pid:number)=>{try{process.kill(pid,0);return true}catch{return false}};
describe("canonical fenced dispatch",()=>{
 test("durable JSON persists the temporary file before rename and the parent directory after",async()=>{const root=await mkdtemp(resolve(tmpdir(),"v3-durable-json-"));roots.push(root);const target=resolve(root,"intent.json"),probe=resolve(root,"probe.ts"),trace=resolve(root,"trace.log");await writeFile(probe,`import {durableJson} from ${JSON.stringify(resolve(import.meta.dir,"dispatcher.ts"))};await durableJson(process.argv[2],{phase:"intended"})`);const run=Bun.spawnSync(["strace","-f","-qq","-o",trace,"-e","trace=openat,fsync,rename,close",process.execPath,probe,target]);expect(run.exitCode).toBe(0);expect(JSON.parse(await readFile(target,"utf8"))).toEqual({phase:"intended"});const calls=(await readFile(trace,"utf8")).split("\n"),openIndex=calls.findIndex(x=>x.includes(`${target}.`)&&x.includes(".tmp")&&x.includes("O_WRONLY|O_CREAT|O_TRUNC")),temporary=calls[openIndex]?.match(/openat\(AT_FDCWD, "([^"]+\.tmp)"/)?.[1],fileFd=calls[openIndex]?.match(/= (\d+)$/)?.[1],fileSyncIndex=calls.findIndex((x,i)=>i>openIndex&&x.includes(`fsync(${fileFd})`)),renameIndex=calls.findIndex(x=>x.includes(`rename(${JSON.stringify(temporary)}, ${JSON.stringify(target)})`)),directoryOpenIndex=calls.findIndex((x,i)=>i>renameIndex&&x.includes(JSON.stringify(root))&&x.includes("O_RDONLY")),directoryFd=calls[directoryOpenIndex]?.match(/= (\d+)$/)?.[1],directorySyncIndex=calls.findIndex((x,i)=>i>directoryOpenIndex&&x.includes(`fsync(${directoryFd})`));expect(openIndex).toBeGreaterThan(-1);expect(fileSyncIndex).toBeGreaterThan(openIndex);expect(renameIndex).toBeGreaterThan(fileSyncIndex);expect(directoryOpenIndex).toBeGreaterThan(renameIndex);expect(directorySyncIndex).toBeGreaterThan(directoryOpenIndex)});
 test("claims once and persists schema-validated commit evidence",async()=>{const o=await fixture();await Promise.all([dispatchOnce(o),dispatchOnce(o)]);const r=row(o.storePath);expect(r.fencingToken).toBe(1);expect(r.terminalVerdict).toBe("clean");expect(await readFile(r.terminalReportPath!,"utf8")).toContain(`commit: ${r.terminalSha}`)});
 test("ack timeout terminates original before retry can launch",async()=>{const o=await fixture(1,[process.execPath,"-e",`process.on('SIGTERM',()=>setTimeout(()=>process.exit(0),80));setInterval(()=>{},100)`]);await dispatchOnce({...o,acknowledgementMs:30});expect(row(o.storePath).state).toBe("ready");const counter=resolve(o.root,"launches");process.env.DISPATCH_COUNTER_PATH=counter;await dispatchOnce({...o,worker:[process.execPath,resolve(import.meta.dir,"../tests/fixtures/noop-worker.ts")]});expect(row(o.storePath).terminalVerdict).toBe("clean");expect((await readFile(counter,"utf8")).trim()).toBe("launch")});
 test("reconciliation kills the real indefinitely-live child from the spawn-to-record crash window",async()=>{const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/never-exit-worker.ts")]),childPidPath=resolve(o.root,"child.pid");process.env.DISPATCH_CHILD_PID_PATH=childPidPath;let wrapperPid=0,childPid=0;
  try{await expect(dispatchOnce({...o,afterSpawnBeforePersist:async()=>{const intentPath=resolve(o.runtimeDir,"lane-1","attempt-1","worker-intent.json");for(let n=0;n<200;n++){try{const i=JSON.parse(await readFile(intentPath,"utf8"));if(i.phase==="identified")wrapperPid=i.pid}catch{}try{childPid=Number(await readFile(childPidPath,"utf8"))}catch{}if(wrapperPid&&childPid)break;await Bun.sleep(5)}expect(row(o.storePath).state).toBe("running");expect(wrapperPid).toBeGreaterThan(0);expect(childPid).toBeGreaterThan(0);expect(pidAlive(wrapperPid)).toBe(true);expect(pidAlive(childPid)).toBe(true);throw new Error("crash window")}})).rejects.toThrow("crash window");
   expect(await reconcileRunning(o)).toBe(1);for(let n=0;n<100&&(pidAlive(wrapperPid)||pidAlive(childPid));n++)await Bun.sleep(10);expect(pidAlive(wrapperPid)).toBe(false);expect(pidAlive(childPid)).toBe(false);expect(row(o.storePath).terminalVerdict).toBe("NO-GO")
  }finally{for(const pid of [wrapperPid,childPid])if(pid&&pidAlive(pid))process.kill(pid,"SIGKILL")}});
 test("recovers a live worker after PID persistence and before release",async()=>{
  const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/gated-worker.ts")]),counter=resolve(o.root,"launches");process.env.DISPATCH_COUNTER_PATH=counter;let pid=0;
  try {
   await expect(dispatchOnce({...o,afterPersistBeforeRelease:async()=>{const intent=JSON.parse(await readFile(resolve(o.runtimeDir,"lane-1","attempt-1","worker-intent.json"),"utf8"));pid=intent.pid;expect(intent.phase).toBe("persisted");expect(pid).toBeGreaterThan(0);expect(await Bun.file(resolve(o.runtimeDir,"lane-1","attempt-1","release")).exists()).toBe(false);expect(pidAlive(pid)).toBe(true);throw new Error("post-pid crash")}})).rejects.toThrow("post-pid crash");
   expect(row(o.storePath).state).toBe("running");expect(await reconcileRunning({...o,terminalMs:5000})).toBe(1);expect(row(o.storePath).terminalVerdict).toBe("clean");
   for(let i=0;i<100&&pidAlive(pid);i++)await Bun.sleep(10);
   expect(pidAlive(pid)).toBe(false);expect((await readFile(counter,"utf8")).trim()).toBe("launch");
  } finally {if(pid&&pidAlive(pid))process.kill(pid,"SIGKILL")}
 });
 test("reconciles a claimed row carrying authentic terminal evidence",async()=>{const o=await fixture();const s=new DurableStore(o.storePath),c=s.claimLane("lane-1","owner",30000),r=s.getLane("lane-1")!;s.close();const dir=resolve(o.runtimeDir,"lane-1",`attempt-${c.fencingToken}`);await Bun.$`mkdir -p ${dir}`;const sha=Bun.spawnSync(["git","rev-parse","HEAD"]).stdout.toString().trim(),report=resolve(dir,"report.md");await writeFile(report,`commit: ${sha}\nverify: true\nresult: clean\nsecret-scan: clean\nremaining: none\n`);await writeFile(resolve(dir,"terminal.json"),JSON.stringify({laneId:"lane-1",attempt:1,ownerToken:"owner",at:new Date().toISOString(),reportPath:report,sha,verdict:"clean"}));expect(await reconcileRunning(o)).toBe(1);expect(row(o.storePath).terminalVerdict).toBe("clean")});
 test("expired owner is fenced by an identified stale-lease takeover",async()=>{const o=await fixture(1),first=new DurableStore(o.storePath,{now:()=>1000});const a=first.claimLane("lane-1","dispatcher-a",10);first.close();const second=new DurableStore(o.storePath,{now:()=>1011}),b=second.claimLane("lane-1","dispatcher-b",10);expect(b.fencingToken).toBe(a.fencingToken+1);expect(()=>second.acknowledgeLane("lane-1","dispatcher-a",a.fencingToken)).toThrow("stale or expired");second.close()});
 test("rejects synthetic SHA, foreign report, and mismatched attempt",async()=>{for(const kind of ["synthetic","foreign","attempt"]){const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/forged-worker.ts"),kind]);await dispatchOnce(o);expect(row(o.storePath).terminalVerdict).toBe("NO-GO");expect(await readFile(row(o.storePath).terminalReportPath!,"utf8")).toContain("terminal evidence invalid")}});
 test("rejects a commit: line whose value is wrong even when the right sha is mentioned elsewhere in the report",async()=>{
  // Regression lock for gate/report-contract.ts: before validTerminal() used
  // its anchored lineValue() parser, a raw `report.includes("commit: <sha>")`
  // substring test would find the sha mentioned inside an unrelated `note:`
  // line and wrongly accept this report even though its actual `commit:`
  // line names a different value. tests/fixtures/forged-worker.ts's
  // "line-injection" kind constructs exactly that report.
  const o=await fixture(0,[process.execPath,resolve(import.meta.dir,"../tests/fixtures/forged-worker.ts"),"line-injection"]);
  await dispatchOnce(o);
  expect(row(o.storePath).terminalVerdict).toBe("NO-GO");
  expect(await readFile(row(o.storePath).terminalReportPath!,"utf8")).toContain("terminal evidence invalid");
 });
});
