// Shared discovery of instruction docs for the checker and the index generator.

import { lstatSync, readdirSync, readFileSync, realpathSync, statSync } from "node:fs";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { parseFrontmatter, validateFrontmatter, type Frontmatter } from "./schema.ts";

export type InstructionDoc = {
  // Absolute path on disk.
  path: string;
  // Path relative to the instructions/ root, for links and stable reporting.
  relative: string;
  contents: string;
  frontmatter: Record<string, unknown> | undefined;
  raw: string | undefined;
  // Populated when the frontmatter is schema-valid.
  valid?: Frontmatter;
};

// The generated index lives at this name and is excluded from doc discovery.
export const INDEX_FILENAME = "README.md";
export const INDEX_MARKER = "<!-- generated by tools/instructions/index.ts -->";

export class PackableInstanceDocError extends Error {
  constructor(message: string) {
    super(`instance/packable-docs.conf: ${message}`);
    this.name = "PackableInstanceDocError";
  }
}

// Recursively collects `*.md` files under the instructions/ root (excluding the
// generated index itself), returning them sorted by relative path for stable
// output. Missing root yields an empty list — the caller decides if that fails.
export function collectDocs(instructionsRoot: string): InstructionDoc[] {
  const docs: InstructionDoc[] = [];
  walk(instructionsRoot, instructionsRoot, docs);
  return docs.sort((a, b) => a.relative.localeCompare(b.relative));
}

// Reads the explicit allowlist for instance documents admitted to instruction
// delivery. Missing config is intentionally empty for fixture/fresh repos.
export function readPackableInstanceDocs(repoRoot: string): string[] {
  const configPath = join(repoRoot, "instance", "packable-docs.conf");
  let contents: string;
  try {
    contents = readFileSync(configPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }

  const instanceRoot = resolve(repoRoot, "instance");
  const seen = new Set<string>();
  const paths: string[] = [];
  for (const [index, raw] of contents.split(/\r?\n/).entries()) {
    const entry = raw.trim();
    if (entry === "" || entry.startsWith("#")) continue;
    const label = `line ${index + 1} '${entry}'`;
    if (seen.has(entry)) throw new PackableInstanceDocError(`${label}: duplicate entry`);
    seen.add(entry);
    if (isAbsolute(entry)) throw new PackableInstanceDocError(`${label}: absolute paths are refused`);
    if (entry.includes("\\")) throw new PackableInstanceDocError(`${label}: backslashes are refused`);
    if (entry.split("/").includes("..")) throw new PackableInstanceDocError(`${label}: '..' segments are refused`);
    if (!entry.endsWith(".md")) throw new PackableInstanceDocError(`${label}: path must end in .md`);

    const resolved = resolve(repoRoot, entry);
    if (!resolved.startsWith(instanceRoot + sep)) {
      throw new PackableInstanceDocError(`${label}: path must resolve strictly under instance/`);
    }
    let stats;
    try {
      stats = lstatSync(resolved);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        throw new PackableInstanceDocError(`${label}: file does not exist`);
      }
      throw error;
    }
    if (!stats.isFile()) {
      throw new PackableInstanceDocError(`${label}: path must be a regular file (symlinks are refused)`);
    }
    if (realpathSync(resolved) !== resolved) {
      throw new PackableInstanceDocError(`${label}: symlinks in the path are refused`);
    }
    paths.push(resolved);
  }
  return paths;
}

export function collectRepoDocs(repoRoot: string): InstructionDoc[] {
  const instructionsRoot = resolve(repoRoot, "instructions");
  const docs = collectDocs(instructionsRoot);
  for (const path of readPackableInstanceDocs(repoRoot)) {
    const contents = readFileSync(path, "utf8");
    const parsed = parseFrontmatter(contents);
    const validation = validateFrontmatter(parsed.frontmatter);
    docs.push({
      path,
      relative: relative(instructionsRoot, path),
      contents,
      frontmatter: parsed.frontmatter,
      raw: parsed.raw,
      valid: validation.valid ? validation.frontmatter : undefined,
    });
  }
  return docs.sort((a, b) => a.relative.localeCompare(b.relative));
}

function walk(root: string, dir: string, out: InstructionDoc[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    const stats = statSync(full);
    if (stats.isDirectory()) {
      walk(root, full, out);
      continue;
    }
    if (!entry.endsWith(".md")) continue;
    const rel = relative(root, full);
    if (rel === INDEX_FILENAME) continue;
    const contents = readFileSync(full, "utf8");
    const parsed = parseFrontmatter(contents);
    const validation = validateFrontmatter(parsed.frontmatter);
    out.push({
      path: full,
      relative: rel,
      contents,
      frontmatter: parsed.frontmatter,
      raw: parsed.raw,
      valid: validation.valid ? validation.frontmatter : undefined,
    });
  }
}
