// Shared discovery of instruction docs for the checker and the index generator.

import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { parseFrontmatter, validateFrontmatter, type Frontmatter } from "./schema.ts";

export type InstructionDoc = {
  // Absolute path on disk.
  path: string;
  // Path relative to the instructions/ root, for links and stable reporting.
  relative: string;
  contents: string;
  frontmatter: Record<string, unknown> | undefined;
  raw: string | undefined;
  // Populated when the frontmatter is schema-valid.
  valid?: Frontmatter;
};

// The generated index lives at this name and is excluded from doc discovery.
export const INDEX_FILENAME = "README.md";
export const INDEX_MARKER = "<!-- generated by tools/instructions/index.ts -->";

// Recursively collects `*.md` files under the instructions/ root (excluding the
// generated index itself), returning them sorted by relative path for stable
// output. Missing root yields an empty list — the caller decides if that fails.
export function collectDocs(instructionsRoot: string): InstructionDoc[] {
  const docs: InstructionDoc[] = [];
  walk(instructionsRoot, instructionsRoot, docs);
  return docs.sort((a, b) => a.relative.localeCompare(b.relative));
}

function walk(root: string, dir: string, out: InstructionDoc[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    const stats = statSync(full);
    if (stats.isDirectory()) {
      walk(root, full, out);
      continue;
    }
    if (!entry.endsWith(".md")) continue;
    const rel = relative(root, full);
    if (rel === INDEX_FILENAME) continue;
    const contents = readFileSync(full, "utf8");
    const parsed = parseFrontmatter(contents);
    const validation = validateFrontmatter(parsed.frontmatter);
    out.push({
      path: full,
      relative: rel,
      contents,
      frontmatter: parsed.frontmatter,
      raw: parsed.raw,
      valid: validation.valid ? validation.frontmatter : undefined,
    });
  }
}
