#!/usr/bin/env bun
//
// Generates instance/README.md — the index of THIS installation's facts and
// retained evidence that CLAUDE.md and HR-735 both route agents to.
//
// Why generated rather than written. HR-735 sends an agent here to check
// whether the operator ALREADY answered something before asking him again, and
// the operator's own objection to the design was the maintenance question:
// «Тільки ж його актуалізовувати треба, не проібеш тут нічого?». A hand-kept
// index answers that question with a promise. This one answers it with a
// mechanism: every list, count and quote below is derived from a tracked source
// at render time, and tools/instructions/check.ts turns red when this file and
// those sources disagree — the same guard that already holds
// instructions/README.md, reused rather than reinvented.
//
// So a row leaves the open-obligations list by being marked `answered` in
// instance/decisions/triage.jsonl. It never leaves by someone editing this file,
// and it cannot be forgotten out of it.
//
// Two boundaries this generator will not cross:
//
//   1. It reads TRACKED files only, enumerated through `git ls-files`. Untracked
//      host state differs per worktree, so reading it would make the freshness
//      comparison answer a different question in every checkout — and would let
//      a lane's scratch file silently redden the suite.
//   2. It never reads instance/decisions/inbox.jsonl. That file is gitignored
//      precisely because raw inbound chat may carry credentials; this file is
//      tracked. The inbox is indexed by path and purpose, and the operator's
//      words reach this file only through triage.jsonl, which is tracked and
//      secret-scanned.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join, relative, resolve } from "node:path";

export const INSTANCE_INDEX_PATH = join("instance", "README.md");
export const INSTANCE_INDEX_MARKER = "<!-- generated by tools/instance/index.ts -->";

// ── Tracked-file enumeration ───────────────────────────────────────────────
//
// Same posture, and the same reason, as tools/instructions/paths.ts: tracked-ness
// is the answer that is identical in the canonical checkout and in every lane
// worktree. Outside a git repository (a fixture, an exported tree) fall back to
// the filesystem rather than rendering nothing — the caller is then a test, not
// the installation.
export type Tree = { under: (prefix: string) => string[]; mode: "git" | "filesystem" };

export function createTree(repo: string): Tree {
  const listed = spawnSync("git", ["-C", repo, "ls-files", "-z"], {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  if (!listed.error && listed.status === 0) {
    const files = listed.stdout.split("\0").filter((entry) => entry !== "").sort();
    return { mode: "git", under: (prefix) => files.filter((file) => file.startsWith(prefix)) };
  }
  return { mode: "filesystem", under: (prefix) => walk(repo, prefix).sort() };
}

function walk(repo: string, prefix: string): string[] {
  const root = join(repo, prefix);
  let entries: string[];
  try {
    entries = readdirSync(root);
  } catch {
    return [];
  }
  const out: string[] = [];
  for (const entry of entries) {
    const full = join(root, entry);
    const rel = relative(repo, full);
    if (statSync(full).isDirectory()) out.push(...walk(repo, rel));
    else out.push(rel);
  }
  return out;
}

// ── Sources ────────────────────────────────────────────────────────────────

export type TriageRow = {
  msg_id: number | string;
  verdict?: string;
  category?: string;
  triaged_at?: string;
  quote?: string;
  answer_status?: string;
};

// Rows the ledger carries. A malformed line is skipped here on purpose: its
// validity is tools/instructions/ledger.ts's job and it already fails closed on
// one. Two checkers disagreeing about one file is the defect, not the coverage.
export function readTriage(repo: string): TriageRow[] {
  const path = join(repo, "instance", "decisions", "triage.jsonl");
  if (!existsSync(path)) return [];
  const rows: TriageRow[] = [];
  for (const line of readFileSync(path, "utf8").split("\n")) {
    if (line.trim() === "") continue;
    try {
      rows.push(JSON.parse(line) as TriageRow);
    } catch {
      continue;
    }
  }
  return rows;
}

// Message ids are numeric in the daemon's mirror and occasionally string in
// hand-captured rows, so compare numerically when both sides parse and fall back
// to a stable string order when they do not.
function byMsgId(a: TriageRow["msg_id"], b: TriageRow["msg_id"]): number {
  const left = Number(a);
  const right = Number(b);
  if (Number.isFinite(left) && Number.isFinite(right) && left !== right) return left - right;
  return String(a).localeCompare(String(b));
}

export type Ruling = { id: string; file: string; date: string; title: string };

export function readRulings(repo: string, tree: Tree): Ruling[] {
  const rulings: Ruling[] = [];
  for (const file of tree.under("instance/decisions/")) {
    const match = file.match(/^instance\/decisions\/HR-(.+)\.md$/);
    if (!match) continue;
    const contents = readFileSync(join(repo, file), "utf8");
    rulings.push({
      id: match[1],
      file,
      date: rulingDate(contents),
      title: headingTitle(contents, match[1]),
    });
  }
  // Newest first BY DATE, not by message id: the Telegram numbering restarted
  // when the bot changed, so the 11xxx ids are the OLDEST rulings, not the
  // newest. Sorting by id put 2026-07-29 at the top of a list whose whole
  // purpose is "what did he decide recently".
  return rulings.sort((a, b) => b.date.localeCompare(a.date) || byMsgId(b.id, a.id));
}

// A ruling's date. The frontmatter `date:` field where the file has one; the
// first ISO date in its opening lines otherwise, which is where the un-
// frontmattered files record it ("Recorded 2026-08-04 from Telegram message …").
// Undated sorts last rather than being silently dropped.
function rulingDate(contents: string): string {
  const field = firstField(contents, "date");
  if (field !== undefined) return field;
  const head = contents.split(/\r?\n/).slice(0, 10).join("\n");
  return head.match(/\d{4}-\d{2}-\d{2}/)?.[0] ?? "(no date)";
}

export type EvidenceItem = { file: string; name: string; title: string };

export function readEvidence(repo: string, tree: Tree, directory: string): EvidenceItem[] {
  const prefix = `instance/${directory}/`;
  const items: EvidenceItem[] = [];
  for (const file of tree.under(prefix)) {
    if (!file.endsWith(".md")) continue;
    const name = file.slice(prefix.length);
    const contents = readFileSync(join(repo, file), "utf8");
    items.push({ file, name, title: headingTitle(contents, "") || name });
  }
  return items;
}

// Documents sitting directly in instance/ — the workboard, the consilium
// records, the in-flight snapshots. Enumerated rather than listed by hand for
// the same reason as everything else here.
export function readRootDocuments(repo: string, tree: Tree): EvidenceItem[] {
  const items: EvidenceItem[] = [];
  for (const file of tree.under("instance/")) {
    if (!file.endsWith(".md")) continue;
    const name = file.slice("instance/".length);
    if (name.includes("/") || name === "README.md") continue;
    const contents = readFileSync(join(repo, file), "utf8");
    items.push({ file, name, title: headingTitle(contents, "") || name });
  }
  return items;
}

export type Credential = {
  id: string;
  location: string;
  identity: string;
  purpose: string;
  provenance: string;
};

export function readCredentials(repo: string): Credential[] {
  const path = join(repo, "instance", "credentials.tsv");
  if (!existsSync(path)) return [];
  const rows: Credential[] = [];
  for (const line of readFileSync(path, "utf8").split("\n")) {
    if (line.trim() === "" || line.startsWith("#")) continue;
    const fields = line.split("\t").map((field) => field.trim());
    if (fields.length !== 5 || fields.some((field) => field === "")) continue;
    const [id, location, identity, purpose, provenance] = fields;
    rows.push({ id, location, identity, purpose, provenance });
  }
  return rows;
}

// Top-level keys of instance/params.yaml. The values are deliberately NOT
// rendered: params.yaml is the one home for them (instruction-layers Q1), and a
// second copy here would be a fact with two homes, which is how they drift.
export function readParamSections(repo: string): string[] {
  const path = join(repo, "instance", "params.yaml");
  if (!existsSync(path)) return [];
  const keys: string[] = [];
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*):/);
    if (match) keys.push(match[1]);
  }
  return keys;
}

export type Mechanism = { id: string; kind: string; target: string };

export function readMechanisms(repo: string): Mechanism[] {
  const path = join(repo, "instance", "required-mechanisms.tsv");
  if (!existsSync(path)) return [];
  const rows: Mechanism[] = [];
  for (const line of readFileSync(path, "utf8").split("\n")) {
    if (line.trim() === "" || line.startsWith("#")) continue;
    const fields = line.split("\t").map((field) => field.trim());
    if (fields.length !== 3 || fields.some((field) => field === "")) continue;
    rows.push({ id: fields[0], kind: fields[1], target: fields[2] });
  }
  return rows;
}

function firstField(contents: string, field: string): string | undefined {
  const match = contents.match(new RegExp(`^${field}\\s*:\\s*(.+)$`, "m"));
  return match ? match[1].trim().replace(/^["']|["']$/g, "") : undefined;
}

// The document's own `# ` heading, with a leading `HR-<id> — ` stripped so the
// rendered line does not say the same identifier twice.
function headingTitle(contents: string, id: string): string {
  const match = contents.match(/^#\s+(.+)$/m);
  if (!match) return "";
  let title = match[1].trim();
  if (id !== "") title = title.replace(new RegExp(`^HR-${escapeRegExp(id)}\\s*[—:-]\\s*`), "");
  return title;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// A verbatim quote rendered as a Markdown blockquote. Hard Floor 2: his words
// are never reworded or trimmed, so nothing here edits the text — line breaks
// get a continuation marker and that is all.
function blockquote(text: string): string[] {
  return text.split(/\r?\n/).map((line) => (line === "" ? ">" : `> ${line}`));
}

function plural(count: number, one: string, many: string): string {
  return count === 1 ? one : many;
}

// ── Rendering ──────────────────────────────────────────────────────────────

export function renderInstanceIndex(repo: string, tree: Tree = createTree(repo)): string {
  const triage = readTriage(repo);
  const directives = triage.filter((row) => row.verdict === "directive");
  const owed = directives
    .filter((row) => row.answer_status === "owed")
    .sort((a, b) => byMsgId(a.msg_id, b.msg_id));
  const unclassified = directives
    .filter((row) => row.answer_status === undefined)
    .sort((a, b) => byMsgId(a.msg_id, b.msg_id));
  const answered = directives.filter((row) => row.answer_status === "answered");
  const rulings = readRulings(repo, tree);
  const credentials = readCredentials(repo);
  const mechanisms = readMechanisms(repo);
  const sections = readParamSections(repo);

  const out: string[] = [INSTANCE_INDEX_MARKER, "# This installation"];

  out.push(
    "",
    "Index of this installation's facts, the operator's words, and the evidence this",
    "repository retains. `CLAUDE.md` names this file as that index; `HR-735` routes an",
    "agent here to find out whether the operator **already answered** a question —",
    "before asking him it again.",
    "",
    "**Generated. Do not edit by hand.** Every list, count and quote below is derived",
    "from a tracked source. Regenerate with `bun tools/instance/index.ts` and commit the",
    "result; `bun tools/instructions/check.ts` goes red when this file and its sources",
    "disagree, so a stale index fails the suite instead of quietly misinforming an agent.",
  );

  // ── Open obligations ─────────────────────────────────────────────────────
  out.push(
    "",
    "## Open obligations — what he asked for and has not been given",
    "",
    "Derived from `instance/decisions/triage.jsonl`: every `verdict: directive` row whose",
    "`answer_status` is still `owed`, with the verbatim words the ledger already stores.",
    "A row leaves this list by being marked `answered` **in the ledger** — never by",
    "editing this file.",
    "",
    `**${owed.length} open** (of ${directives.length} directives captured; ${answered.length} answered).`,
  );
  if (owed.length === 0) {
    out.push("", "Nothing owed.");
  } else {
    for (const row of owed) {
      out.push("", `- **${row.msg_id}** · ${row.triaged_at ?? "(no date)"} · \`${row.category ?? "-"}\``);
      out.push(...blockquote(row.quote ?? "").map((line) => `  ${line}`));
    }
  }

  out.push(
    "",
    "### Directives carrying no answer status",
    "",
    "A directive with no `answer_status` is in neither list above: not owed, not",
    "answered, unaccounted for. They are named here so the gap cannot hide in the",
    "difference between two counts.",
    "",
  );
  if (unclassified.length === 0) {
    out.push("None — every captured directive is classified.");
  } else {
    out.push(
      `**${unclassified.length} unclassified:** ` +
        unclassified.map((row) => `\`${row.msg_id}\``).join(", ") +
        ".",
    );
  }

  // ── Where his words live ─────────────────────────────────────────────────
  out.push(
    "",
    "## Where his words live",
    "",
    "| source | tracked? | what it holds |",
    "|---|---|---|",
    "| `instance/decisions/inbox.jsonl` | **no — gitignored, host-only** | the raw inbound mirror. Untriaged chat, which may carry credentials; that is why it is ignored and why nothing copies out of it. Indexed here by path and purpose only. |",
    `| \`instance/decisions/triage.jsonl\` | yes | the triaged ledger: ${triage.length} rows, each with a verbatim \`quote\`, a \`chatter\`/\`directive\` verdict and category-only tokens. Secret-scanned, and the source of the obligations list above. |`,
    `| \`instance/decisions/HR-<msg-id>.md\` | yes | ${rulings.length} rulings, each opening with his words verbatim under its own heading, followed by a separately labelled generated summary. |`,
    "| `instance/cast.md`, `instance/channels.md` | yes | who the parties are, and the addresses this installation reaches them at. |",
    "",
    "### Where the full Telegram history actually lives",
    "",
    "Named by `HR-735` as a place to check before asking him anything. The honest",
    "answer is that **no single complete transcript exists in this repository**, so",
    "check in this order:",
    "",
    "1. `instance/decisions/triage.jsonl` — the only tracked, complete-by-intent record",
    "   of his words. One row per triaged message, quote included.",
    "2. `instance/decisions/HR-*.md` — the rulings, in full, where a message decided",
    "   something.",
    "3. `~/.claude/channels/telegram/history/messages-YYYY-MM.jsonl` — host-only, and",
    "   **metadata only**: timestamps, direction, outcome, length and a content hash.",
    "   The message text is not there. Retention and size caps are set in",
    "   `daemon/history-logger.ts`, so old months are deleted on their own.",
    "4. The v1 orchestrator, which holds the older history: reach it through the file",
    "   channel in `instance/channels.md`, not through the branch that looks like it.",
    "",
    "If a question survives all four, it is genuinely unanswered and `HR-735` permits",
    "asking it.",
  );

  // ── Rulings ──────────────────────────────────────────────────────────────
  out.push(
    "",
    `## His rulings — ${rulings.length} of them`,
    "",
    "`instance/decisions/HR-<telegram-msg-id>.md`, newest first.",
    "",
  );
  for (const ruling of rulings) {
    out.push(`- [HR-${ruling.id}](decisions/HR-${ruling.id}.md) · ${ruling.date} · ${ruling.title}`);
  }

  // ── Installation facts ───────────────────────────────────────────────────
  const checkers = mechanisms.filter((row) => row.kind === "checker");
  const units = mechanisms.filter((row) => row.kind === "systemd");
  out.push(
    "",
    "## Facts about this installation",
    "",
    `- \`instance/params.yaml\` — the parameter file, and the one home for every value in it. ${sections.length} ${plural(sections.length, "section", "sections")}: ${sections.map((key) => `\`${key}\``).join(", ")}. Values are deliberately not copied here; a fact with two homes is a fact that drifts.`,
    `- \`instance/required-mechanisms.tsv\` and \`instance/expected-mechanisms.tsv\` — two independently maintained inventories of what must exist: ${units.length} systemd ${plural(units.length, "unit", "units")}, ${checkers.length} ${plural(checkers.length, "checker", "checkers")}, plus the gate, the cron and the runners. \`tools/check-mechanism-reachability.ts\` refuses when they disagree, when a target is missing, or when a mechanism nothing can reach is still listed.`,
    "- `instance/expected-units.tsv` with `instance/units/*.in` and `bootstrap/units/*.in` — the unit templates this host renders, pinned independently so deleting a template cannot shrink the truth. `bootstrap/check-unit-drift.sh` compares rendered units against the installed ones.",
    "- `instance/packs.conf`, `instance/tags.conf` — which instruction docs each role's mission pack carries.",
    "- `instance/workboard.md` — the live board: every row, its acceptance, and its state.",
    "",
    "The checkers that enumerate and verify parts of this installation:",
    "",
  );
  for (const checker of checkers) {
    out.push(`- \`${checker.target}\``);
  }
  out.push(
    "",
    "**Not yet true, and stated here rather than implied:** there is no complete",
    "enumeration of the non-git host state — the state database, mission and lane",
    "history, durable evidence outside this tree. That is workboard row **V3-2.9**, open.",
    "Until it exists, this section indexes what the repository knows about itself, not",
    "everything the host holds.",
  );

  // ── Credentials ──────────────────────────────────────────────────────────
  out.push(
    "",
    "## Credentials — which exist, and where they live",
    "",
    "From `instance/credentials.tsv`. **Locations, identities and purposes only — never",
    "a value.** This is the section that exists so the question stops being asked; the",
    "required scope, the rotation procedure and a verification command per credential",
    "are workboard row **V3-2.10**, still open.",
    "",
    "| credential | location | identity | purpose | provenance |",
    "|---|---|---|---|---|",
  );
  for (const credential of credentials) {
    out.push(
      `| \`${credential.id}\` | \`${credential.location}\` | ${credential.identity} | ${credential.purpose} | ${credential.provenance} |`,
    );
  }

  // ── Retained evidence ────────────────────────────────────────────────────
  out.push("", "## Retained evidence");
  const groups: Array<{ directory: string; heading: string; note: string }> = [
    { directory: "incidents", heading: "Incidents", note: "what broke, and what the repair was." },
    { directory: "audits", heading: "Audits", note: "findings against the system itself." },
    {
      directory: "parked",
      heading: "Parked rows",
      note: "work stopped deliberately, with the evidence that stopped it.",
    },
    { directory: "sprints", heading: "Sprints", note: "what was planned, and what closing it found." },
    { directory: "specs", heading: "Specs", note: "designs written before their implementation." },
  ];
  for (const group of groups) {
    const items = readEvidence(repo, tree, group.directory);
    out.push("", `### ${group.heading} — ${items.length} (\`instance/${group.directory}/\`)`, "", group.note, "");
    if (items.length === 0) out.push("_(empty)_");
    for (const item of items) {
      out.push(`- [${item.name}](${group.directory}/${item.name}) — ${item.title}`);
    }
  }

  const rootDocuments = readRootDocuments(repo, tree);
  out.push(
    "",
    `### Documents at the root of \`instance/\` — ${rootDocuments.length}`,
    "",
    "Consilium records, in-flight snapshots, the board, and the standing this-installation documents.",
    "",
  );
  for (const document of rootDocuments) {
    out.push(`- [${document.name}](${document.name}) — ${document.title}`);
  }

  return out.join("\n") + "\n";
}

// Only run the CLI when executed directly, not when imported — check.ts reuses
// renderInstanceIndex for its freshness comparison and must never write a file.
if (import.meta.main) {
  const args = process.argv.slice(2);
  let repo = process.cwd();
  let write = true;
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "-h" || arg === "--help") {
      process.stdout.write(
        [
          "Usage: bun tools/instance/index.ts [--repo <path>] [--check]",
          "",
          "  --repo <path>   Repository root (default: current directory)",
          "  --check         Print the index to stdout without writing the file",
          "  -h, --help      Show this usage",
          "",
        ].join("\n"),
      );
      process.exit(0);
    }
    if (arg === "--check") {
      write = false;
      continue;
    }
    if (arg === "--repo") {
      const value = args[index + 1];
      if (!value || value.startsWith("--")) {
        process.stderr.write("index: --repo requires a path\n");
        process.exit(2);
      }
      repo = value;
      index += 1;
      continue;
    }
    process.stderr.write(`index: unknown argument '${arg}'\n`);
    process.exit(2);
  }

  const root = resolve(repo);
  const rendered = renderInstanceIndex(root);
  if (write) {
    writeFileSync(join(root, INSTANCE_INDEX_PATH), rendered);
    console.log(`wrote ${INSTANCE_INDEX_PATH}`);
  } else {
    process.stdout.write(rendered);
  }
}
