#!/usr/bin/env bun
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type RecordFile = { lane: string; worktree: string; port: number; project: string; image: string; url: string };

const root = process.env.PREVIEW_STATE_ROOT ?? "/var/lib/bpa-previews";
const routes = process.env.PREVIEW_ROUTES_DIR ?? `${root}/routes`;
const domain = process.env.PREVIEW_DOMAIN ?? "localhost";
const minPort = Number(process.env.PREVIEW_PORT_MIN ?? 13000);
const maxPort = Number(process.env.PREVIEW_PORT_MAX ?? 13999);
const appMemory = process.env.PREVIEW_APP_MEMORY ?? "1g";
const appCpus = process.env.PREVIEW_APP_CPUS ?? "0.75";
const dbMemory = process.env.PREVIEW_DB_MEMORY ?? "512m";
const dbCpus = process.env.PREVIEW_DB_CPUS ?? "0.25";

function fail(message: string): never { throw new Error(message); }
function run(args: string[], options: { cwd?: string; quiet?: boolean } = {}) {
  const result = Bun.spawnSync(args, { cwd: options.cwd, stdout: options.quiet ? "ignore" : "inherit", stderr: options.quiet ? "ignore" : "inherit" });
  if (result.exitCode !== 0) fail(`command failed (${result.exitCode}): ${args.join(" ")}`);
  return result;
}
function output(args: string[]) {
  const result = Bun.spawnSync(args, { stdout: "pipe", stderr: "pipe" });
  if (result.exitCode !== 0) return "";
  return result.stdout.toString().trim();
}
function validLane(value: string) { return /^[a-z0-9][a-z0-9-]{0,31}$/.test(value); }
function recordPath(lane: string) { return `${root}/${lane}/record.json`; }
function load(lane: string): RecordFile | undefined {
  const path = recordPath(lane);
  return existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : undefined;
}
function records(): RecordFile[] {
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isDirectory() && entry.name !== "routes")
    .map((entry) => load(entry.name)).filter((record): record is RecordFile => Boolean(record));
}
function assertPort(port: number) {
  if (!Number.isInteger(port) || port < 1024 || port > 65535 || port === 3000 || port === 4822) fail(`unsafe preview port: ${port}`);
}
function allocatePort() {
  const used = new Set(records().map((record) => record.port));
  for (let port = minPort; port <= maxPort; port++) {
    assertPort(port);
    if (!used.has(port) && !output(["docker", "ps", "--quiet", "--filter", `publish=${port}`])) return port;
  }
  fail(`no free preview port in ${minPort}-${maxPort}`);
}
function reloadEdge() {
  if (process.env.PREVIEW_SKIP_EDGE_RELOAD === "1") return;
  run((process.env.PREVIEW_EDGE_RELOAD ?? "systemctl reload bpa-edge.service").split(" "));
}
function routeText(lane: string, port: number) {
  return `# generated by preview/preview.ts\nhandle /preview/${lane}/api/integrations/*/callback {\n  respond 404\n}\nhandle /preview/${lane}/api/integrations/*/connect {\n  respond 404\n}\nhandle_path /preview/${lane}/* {\n  reverse_proxy 127.0.0.1:${port}\n}\n`;
}
function stop(lane: string, tolerateMissing = false) {
  if (!validLane(lane)) fail(`invalid lane name: ${lane}`);
  const record = load(lane);
  if (!record) { if (tolerateMissing) return; fail(`preview not found: ${lane}`); }
  Bun.spawnSync(["docker", "rm", "--force", `${record.project}-app`, `${record.project}-db`], { stdout: "ignore", stderr: "ignore" });
  Bun.spawnSync(["docker", "network", "rm", record.project], { stdout: "ignore", stderr: "ignore" });
  if (record.image) Bun.spawnSync(["docker", "image", "rm", record.image], { stdout: "ignore", stderr: "ignore" });
  const residual = output(["docker", "ps", "--all", "--quiet", "--filter", `label=bpa.preview.lane=${lane}`]);
  if (residual) fail(`preview teardown left containers: ${residual}`);
  rmSync(`${routes}/${lane}.caddy`, { force: true });
  reloadEdge();
  rmSync(`${root}/${lane}`, { recursive: true, force: true });
  console.log(`STOPPED lane=${lane} port=${record.port} state=released`);
}
function start(lane: string, worktreeArg: string) {
  if (!validLane(lane)) fail(`invalid lane name: ${lane}`);
  const worktree = resolve(worktreeArg);
  if (!existsSync(`${worktree}/.git`)) fail(`not a git worktree: ${worktree}`);
  const dockerfile = resolve(process.env.PREVIEW_DOCKERFILE ?? `${worktree}/Dockerfile`);
  if (!existsSync(dockerfile)) fail(`Dockerfile missing: ${dockerfile}`);
  if (load(lane)) fail(`preview already exists: ${lane}`);
  mkdirSync(routes, { recursive: true, mode: 0o755 });
  const laneState = `${root}/${lane}`;
  mkdirSync(`${laneState}/app`, { recursive: true, mode: 0o700 });
  const project = `bpa-preview-${lane}`;
  const image = `${project}:${output(["git", "-C", worktree, "rev-parse", "--short=12", "HEAD"]) || "working"}`;
  const port = allocatePort();
  const containerPort = Number(process.env.PREVIEW_CONTAINER_PORT ?? 3000);
  assertPort(port);
  const dbPassword = crypto.randomUUID().replaceAll("-", "");
  const database = `preview_${lane.replaceAll("-", "_")}`;
  const url = `https://${domain}/preview/${lane}/`;
  const record: RecordFile = { lane, worktree, port, project, image, url };
  writeFileSync(recordPath(lane), `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
  try {
    run(["docker", "build", "-f", dockerfile, "--label", "bpa.preview=true", "--label", `bpa.preview.lane=${lane}`, "-t", image, worktree]);
    run(["docker", "network", "create", "--label", "bpa.preview=true", project]);
    run(["docker", "run", "-d", "--name", `${project}-db`, "--network", project, "--label", "bpa.preview=true", "--label", `bpa.preview.worktree=${worktree}`, "--memory", dbMemory, "--cpus", dbCpus, "--pids-limit", "128", "--health-cmd", `pg_isready -U preview -d ${database}`, "--health-interval", "2s", "--health-timeout", "2s", "--health-retries", "30", "-e", `POSTGRES_DB=${database}`, "-e", "POSTGRES_USER=preview", "-e", `POSTGRES_PASSWORD=${dbPassword}`, "postgres:16-alpine"]);
    let databaseReady = false;
    for (let attempt = 0; attempt < 60; attempt++) {
      if (output(["docker", "inspect", "--format", "{{.State.Health.Status}}", `${project}-db`]) === "healthy") { databaseReady = true; break; }
      Bun.sleepSync(1000);
    }
    if (!databaseReady) fail(`preview database did not become healthy: ${lane}`);
    run(["docker", "run", "-d", "--name", `${project}-app`, "--network", project, "--label", "bpa.preview=true", "--label", `bpa.preview.worktree=${worktree}`, "--memory", appMemory, "--cpus", appCpus, "--pids-limit", "256", "--read-only", "--tmpfs", "/tmp:rw,noexec,nosuid,size=64m", "-v", `${laneState}/app:/preview-state`, "-p", `127.0.0.1:${port}:${containerPort}`, "-e", `PORT=${containerPort}`, "-e", `DATABASE_URL=postgresql://preview:${dbPassword}@${project}-db:5432/${database}`, "-e", "APP_STATE_DIR=/preview-state", "-e", `APP_BASE_PATH=/preview/${lane}`, "-e", `PREVIEW_CONTENT=${lane}`, "-e", "INTEGRATIONS_MODE=NOT-CONFIGURED", "-e", "OAUTH_CALLBACKS_ENABLED=false", image]);
    writeFileSync(`${routes}/${lane}.caddy`, routeText(lane, port), { mode: 0o644 });
    reloadEdge();
    let ready = false;
    for (let attempt = 0; attempt < 60; attempt++) {
      if (Bun.spawnSync(["curl", "--fail", "--silent", `http://127.0.0.1:${port}/`], { stdout: "ignore", stderr: "ignore" }).exitCode === 0) { ready = true; break; }
      Bun.sleepSync(1000);
    }
    if (!ready) fail(`preview did not answer within 60 seconds: ${lane}`);
    console.log(`STARTED lane=${lane} port=${port} url=${url} worktree=${worktree}`);
  } catch (error) {
    Bun.spawnSync(["docker", "rm", "--force", `${project}-app`, `${project}-db`], { stdout: "ignore", stderr: "ignore" });
    Bun.spawnSync(["docker", "network", "rm", project], { stdout: "ignore", stderr: "ignore" });
    rmSync(`${routes}/${lane}.caddy`, { force: true }); rmSync(laneState, { recursive: true, force: true });
    throw error;
  }
}
function list() {
  const all = records();
  if (!all.length) return console.log("PREVIEWS none");
  for (const record of all) console.log(`PREVIEW lane=${record.lane} port=${record.port} url=${record.url} worktree=${record.worktree} running=${Boolean(output(["docker", "ps", "--quiet", "--filter", `name=^/${record.project}-app$`]))}`);
}
function reap() {
  let count = 0;
  for (const record of records()) if (!existsSync(record.worktree)) { stop(record.lane, true); count++; }
  console.log(`REAPED previews=${count}`);
}

const [command, lane, worktree] = process.argv.slice(2);
mkdirSync(root, { recursive: true, mode: 0o755 });
const mutates = command === "start" || command === "stop" || command === "reap";
const lock = `${root}/.operation-lock`;
if (mutates) {
  try { mkdirSync(lock); } catch { fail("another preview lifecycle operation is running"); }
}
try {
  if (command === "start" && lane && worktree) start(lane, worktree);
  else if (command === "stop" && lane) stop(lane);
  else if (command === "list") list();
  else if (command === "reap") reap();
  else { console.log("Usage: preview.ts start <lane> <worktree> | list | stop <lane> | reap"); process.exit(command === "--help" || command === "help" ? 0 : 2); }
} catch (error) {
  console.error(`ERROR: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
} finally {
  if (mutates) rmSync(lock, { recursive: true, force: true });
}
