"""Explicit checkout lifecycle contract; transport implementation is injected."""
from typing import Protocol

class CheckoutLifecycle(Protocol):
    def capture_source(self) -> str: ...
    def checkout(self, target_commit: str) -> None: ...
    def current_commit(self) -> str: ...
    def current_image_digest(self) -> str: ...
